### ISSUE TITLE
Significance of ACOUSTIC_MAX_LEN and VISUAL_MAX_LEN values

### ISSUE THREAD

**Issue by gak97** [mohit2b/MO-Sarcation#1]
What is the significance of the ACOUSTIC_MAX_LEN and VISUAL_MAX_LEN values and how is it different from ACOUSTIC_DIM and VISUAL_DIM values respectively?

ACOUSTIC_DIM = 768
ACOUSTIC_MAX_LEN = 1000

VISUAL_DIM = 2048
VISUAL_MAX_LEN = 480

**Comment by mohit2b** [comment]
@gak97 you can relate ACOUSTIC_MAX_LEN and VISUAL_MAX_LEN to text sequence length. Let's say we have 3 sentences having 3, 4, and 5 words. Then in vectorized form it would be represented as [batch, max_seq_len] so it will be [3,5] since we have 3 sentences and 5 is max seq len. In similar analogy let's say you speak a sentence it will be of some seconds, so the audio has got its own sequence length (along time dimension) and when we discretize it then the maximum length audio is represented by ACOUSTIC_MAX_LEN. And as for video VISUAL_MAX_LEN is the maximum number of frames the video has for a given sampling rate.

It is different from Acoustic dimension in the way that acoustic dimension represents the embedding of audio while ACOUSTIC_MAX_LEN just gives you number of discretize audio tokens and not its embedding. Same applies to VISUAL_MAX_LEN as VISUAL_MAX_LEN gives number of frames for a video while VISUAL_DIM is embedding for each frame.

**Comment by gak97** [comment]
@mohit2b I am using audio files of varying lengths (some are 30 seconds long and some are 5 minutes long). I am taking their embeddings using Wav2Vec2 and using them in the model. How do I configure the `ACOUSTIC_MAX_LEN` in that case?

**Comment by mohit2b** [comment]
> @mohit2b I am using audio files of varying lengths (some are 30 seconds long and some are 5 minutes long). I am taking their embeddings using Wav2Vec2 and using them in the model. How do I configure the `ACOUSTIC_MAX_LEN` in that case?

@gak97  First sample the audio file using Librosa at 16kHz and then pass it through Wave2Vec2, the maximum length audio signal will be used to define ACOUSTIC_MAX_LEN. Check this file for audio preprocessing - https://github.com/thuiar/MIntRec/blob/main/tools/audio_preprocess.py 

For knowing ACOUSTIC_MAX_LEN pass a single audio signal to wave2vec model. Its embedding will be of shape [sequence_length, model_dimension], for every audio file check which file has maximum sequence length and set  ACOUSTIC_MAX_LEN equal to maximum sequence length.

For audio signals that have length less than ACOUSTIC_MAX_LEN pad them with zero, check this code 

```
def pad_seq(tensor, dim, max_len):
  if max_len > tensor.shape[0] :
    return torch.cat([tensor, torch.zeros(max_len - tensor.shape[0], dim)])
  else:
    return tensor[:max_len]
```
Load audio data and try out this code

```
audio_data_utterance = torch.stack([pad_seq(torch.tensor(a, dtype = torch.float),
                                                   dim = ACOUSTIC_DIM,
                                                   max_len = ACOUSTIC_MAX_LEN)
                                                  for a in audio_data_utterance], 0)

```

**Comment by gak97** [comment]
Thanks for the clarification!
